# Generated by Django 6.0.7 on 2026-07-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
